dist: trusty
before_install:
- sudo apt-get update
- sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra
  texlive-fonts-extra texlive-latex-recommended latex-xcolor pgf dvipng chktex rubber
script:
- cd constitution
- chktex -W
- chktex -q -n 6 -n 36 *.tex 2>/dev/null | tee lint.out
- test ! -s lint.out
before_deploy:
- rubber -d constitution
deploy:
  provider: releases
  file: constitution.pdf
  skip_cleanup: true
  edge: true
  on:
    tags: true
    repo: PyconUK/ukpa-constitution
env:
  global:
    secure: 1ZzrbacRnXQPQcLunJPH6EbjvEwFt5eP3hdtmux152Wu9uIGbOtQDMcJXp13KMoxuY5gEuBvAnLqSIyweJ/3GaMpzKluTErDcyP6DST4R9UviNLQI+f13rb1UYGU0g3HipSd9nNo2MwpBWv0s4nF6iRw4SDApB9Tt4kiRdzoPKx8X7hmPZIpm6oEvaCmcCJ6Hll14+MEly+Odsbgkk4j/KebkEyjsanUvslgplW2hmn6dKONW/XInLIZbS5e2DzRLZjZlwHCw+uh68bNJoTwUqIkuxd3sSlPTOPHLYDFwVKIEuhrrExC1p4juAb7e944rzTLF8lLV3eNc6UvGEfVNPqz3KPp/mxCuhW67MMdWj1VrKqDLEAZDYXFgEiMAmWQ9ShlB4i9Wo7XCnyUhVYgfO0DdKh+RjvvfxglrVxx4IZaJR0ovUVOINOzVtqR/ZDNFw2V5TMYgfxsMhLcZfgacIbfv+LNkiW7QU4W+eKEHokvTYnFb+BtliBkAhYidc2Z+WPr+M/DzGghe8p+qZexmg86W7BQIgc2QnaSt9G4iQ3J/BXRhWyAq/G7pgGiax2riHHHv1q3EQTztV0cM4EqkivB7H1vtBBa0G8V2O1O9+5vLTa/O+TdBLT/7DF+hY4kMtHRL0P2GPNKiDqWt3zVwBp70usSSlfW9RISa9nSeZs=
